{'RecordDetails': {'Collection accession number': {'FieldType': 'E',
                                                   'Value': 'CECT 9765'},
                   'Collection date': {'FieldType': 'H', 'Value': '2016-01-01'},
                   'Collector': {'FieldType': 'E', 'Value': 'Oueslati, M.'},
                   'Coordinates of geographic origin': {'FieldType': 'L',
                                                        'Value': {'Latitude': 36.649778,
                                                                  'Longitude': 10.587167}},
                   'Country': {'FieldType': 'RLink',
                               'Value': [{'Name': {'FieldType': 'E',
                                                   'Value': 'Tunisia'},
                                          'RecordId': 116}]},
                   'Deposit date': {'FieldType': 'H', 'Value': '2018-11-15'},
                   'Depositor': {'FieldType': 'E',
                                 'Value': 'Magdalena Mulet, Universitat de les Illes Balears. Facultat de Ciències, PALMA DE MALLORCA, Spain.'},
                   'Dual use': {'FieldType': 'T', 'Value': 'no'},
                   'Form': {'FieldType': 'C',
                            'Value': [{'Name': 'Agar', 'Value': 'yes'},
                                      {'Name': 'Cryo', 'Value': 'no'},
                                      {'Name': 'Dry Ice', 'Value': 'no'},
                                      {'Name': 'Liquid Culture Medium',
                                       'Value': 'no'},
                                      {'Name': 'Lyo', 'Value': 'yes'},
                                      {'Name': 'Oil', 'Value': 'no'},
                                      {'Name': 'Water', 'Value': 'no'}]},
                   'GMO': {'FieldType': 'V', 'Value': 'No'},
                   'Geographic origin': {'FieldType': 'E',
                                         'Value': 'TUN;Beni Khalled (Nabeul)'},
                   'History': {'FieldType': 'E',
                               'Value': 'M. Mulet, Univ. Illes Balears, Spain'},
                   'Isolation date': {'FieldType': 'H', 'Value': '2016-01-01'},
                   'Isolator': {'FieldType': 'E', 'Value': 'Oueslati, M.'},
                   'MTA files URL': {'FieldType': 'U',
                                     'Value': [{'Name': 'link',
                                                'Value': 'http://www.uv.es/cect2/2_MTAen.pdf'}]},
                   'Nagoya protocol restrictions and compliance conditions': {'FieldType': 'T',
                                                                              'Value': 'no known restrictions under the Nagoya protocol'},
                   'Organism type': {'FieldType': 'C',
                                     'Value': [{'Name': 'Algae', 'Value': 'no'},
                                               {'Name': 'Archaea',
                                                'Value': 'no'},
                                               {'Name': 'Bacteria',
                                                'Value': 'yes'},
                                               {'Name': 'Cyanobacteria',
                                                'Value': 'no'},
                                               {'Name': 'Filamentous Fungi',
                                                'Value': 'no'},
                                               {'Name': 'Phage', 'Value': 'no'},
                                               {'Name': 'Plasmid',
                                                'Value': 'no'},
                                               {'Name': 'Virus', 'Value': 'no'},
                                               {'Name': 'Yeast',
                                                'Value': 'no'}]},
                   'Other culture collection numbers': {'FieldType': 'E',
                                                        'Value': 'CFBP 8661'},
                   'Other denomination': {'FieldType': 'E', 'Value': 'E10B'},
                   'Ploidy': {'FieldType': 'T', 'Value': 'Haploid'},
                   'Quarantine in Europe': {'FieldType': 'T', 'Value': 'no'},
                   'Recommended growth medium': {'FieldType': 'RLink',
                                                 'Value': [{'Name': {'FieldType': 'E',
                                                                     'Value': 'LB MEDIUM (Luria Bertani Medium)'},
                                                            'RecordId': 682}]},
                   'Recommended growth temperature': {'FieldType': 'S',
                                                      'MaxValue': 30.0,
                                                      'MinValue': 30.0},
                   'Restrictions on use': {'FieldType': 'T',
                                           'Value': 'for commercial development a special agreement is requested'},
                   'Risk group': {'FieldType': 'T', 'Value': '1'},
                   'Status': {'FieldType': 'E', 'Value': 'type of Pseudomonas'},
                   'Strain from a registered collection': {'FieldType': 'T',
                                                           'Value': 'no'},
                   'Substrate of isolation': {'FieldType': 'E',
                                              'Value': 'Citrus limon Eureka'},
                   'Taxon name': {'FieldType': 'SynLink',
                                  'Value': [{'Name': {'FieldType': 'E',
                                                      'Value': 'Pseudomonas'},
                                             'RecordId': 100001527}]}},
 'RecordId': 140368,
 'RecordName': 'MIRRI0140362'}
